name: lms
description: "LMS"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.2
  sizer: ^3.1.3
  lottie: ^3.3.2
  animated_bottom_navigation_bar: ^1.4.0
  connectivity_plus: ^7.0.0
  dio: ^5.9.0

  flutter_secure_storage: ^9.2.4
  local_auth: ^3.0.0

  firebase_crashlytics: ^5.0.5
  firebase_remote_config: ^6.1.2
  firebase_analytics: ^12.0.4
  firebase_core: ^4.2.1

  syncfusion_flutter_datagrid: ^32.1.19
  flutter_gen: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.12.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo/